--CREATE DATABASE TrainA

USE TRAINA
GO

CREATE TABLE NHANVIEN
(
	MA_NV CHAR(5),
	TEN_NV NVARCHAR(30) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH VARCHAR(3) NOT NULL,
	MATKHAU VARCHAR(30) NOT NULL,
	VAITRO NVARCHAR(20),
	MA_VITRI CHAR(3) NOT NULL, --FK
	CONSTRAINT PK_NV PRIMARY KEY(MA_NV),
	CONSTRAINT CONS_GIOITINH CHECK(GIOITINH IN(N'Nam', N'Nữ')),
	CONSTRAINT CONS_VITRI CHECK(VAITRO IN(N'Admin', N'Quản lý', N'Trainer', N'Trainee', NULL))
)
GO

CREATE TABLE VITRI
(
	MA_VT CHAR(3),
	TEN_VT NVARCHAR(30) NOT NULL,
	MA_PHONGBAN CHAR(3) NOT NULL, --FK
	CONSTRAINT PK_VT PRIMARY KEY(MA_VT)
)
GO

CREATE TABLE PHONGBAN
(
	MA_PB CHAR(3),
	TEN_PB NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_PB PRIMARY KEY(MA_PB)
)
GO

CREATE TABLE DUAN
(
	MA_DA CHAR(3),
	TEN_DA NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_DA PRIMARY KEY(MA_DA)
)
GO

CREATE TABLE KINANG
(
	MA_KN CHAR(3),
	TEN_KN NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_KN PRIMARY KEY(MA_KN)
)
GO

CREATE TABLE KIENTHUC
(
	MA_KT CHAR(3),
	TEN_KT NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_KT PRIMARY KEY(MA_KT)
)
GO

CREATE TABLE LOPHOC
(
	MA_LH CHAR(5),
	TEN_LH NVARCHAR(30) NOT NULL,
	MA_VITRI CHAR(3), --FK
	TG_BATDAU DATE NOT NULL,
	TG_KETHUC DATE,
	CONSTRAINT PK_LH PRIMARY KEY(MA_LH)
)
GO

CREATE TABLE KHOAHOC
(
	MA_KH CHAR(5),
	TEN_KH NVARCHAR(30) NOT NULL,
	MUCTIEU NVARCHAR(100),
	HINH_THUC VARCHAR(7) NOT NULL,
	GHI_CHU NVARCHAR(100),
	CONSTRAINT PK_KH PRIMARY KEY(MA_KH),
	CONSTRAINT CONS_HINH_THUC CHECK(HINH_THUC IN('online', 'offline'))
)
GO

CREATE TABLE NOIDUNG
(
	MA_ND CHAR(5),
	TEN_ND NVARCHAR(30) NOT NULL,
	THOILUONG INT NOT NULL,
	MA_KHOAHOC CHAR(5),
	CONSTRAINT PK_ND PRIMARY KEY(MA_ND)
)
GO

CREATE TABLE TAILIEU
(
	MA_TL CHAR(5),
	TEN_TL NVARCHAR(20) NOT NULL,
	NOIDUNG NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_TL PRIMARY KEY(MA_TL)
)
GO

CREATE TABLE DETHI
(
	MA_DT CHAR(7),
	TEN_DT NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_DT PRIMARY KEY(MA_DT)
)
GO

CREATE TABLE DETULUAN
(
	MA_DTL CHAR(9),
	CAUHOI_TL NVARCHAR(200) NOT NULL,
	DAPAN NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_DTL PRIMARY KEY(MA_DTL)
)
GO

CREATE TABLE DETRACNGHIEM
(
	MA_DTN CHAR(9),
	CAUHOI_TN NVARCHAR(200) NOT NULL,
	DAPAN1 NVARCHAR(50) NOT NULL,
	DAPAN2 NVARCHAR(50) NOT NULL,
	DAPAN3 NVARCHAR(50) NOT NULL,
	DAPAN4 NVARCHAR(50) NOT NULL,
	DAPANDUNG INT NOT NULL,
	CONSTRAINT PK_DTN PRIMARY KEY(MA_DTN)
)
GO

CREATE TABLE CHITIET_LH
(
	MA_LOPHOC CHAR(5), --FK
	MA_KHOAHOC CHAR(5), --FK
	CONSTRAINT PK_LH PRIMARY KEY(MA_LOPHOC, MA_KHOAHOC)
)
GO