--CREATE DATABASE TrainA

USE TRAINA
GO

CREATE TABLE NHANVIEN
(
	MA_NV CHAR(5),
	TEN_NV NVARCHAR(30) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH BIT NOT NULL, --0 LÀ NAM, 1 LÀ NỮ
	MATKHAU VARCHAR(30) NOT NULL,
	VAITRO NVARCHAR(20),
	MA_VITRI CHAR(3) NOT NULL, --FK
	MA_PHONGBAN CHAR(3) NOT NULL, --FK
	CONSTRAINT PK_NV PRIMARY KEY(MA_NV),
	CONSTRAINT CONS_VAITRO CHECK(VAITRO IN(N'Admin', N'Quản lý', N'Trainer', N'Trainee', NULL))
)
GO

CREATE TABLE VITRI
(
	MA_VT CHAR(3),
	TEN_VT NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_VT PRIMARY KEY(MA_VT)
)
GO

CREATE TABLE PHONGBAN
(
	MA_PB CHAR(3),
	TEN_PB NVARCHAR(30) NOT NULL,
	MOTA NVARCHAR(100),
	CONSTRAINT PK_PB PRIMARY KEY(MA_PB)
)
GO

CREATE TABLE DUAN
(
	MA_DA CHAR(3),
	TEN_DA NVARCHAR(30) NOT NULL,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	NOIDUNG NVARCHAR(100),
	CONSTRAINT PK_DA PRIMARY KEY(MA_DA)
)
GO

CREATE TABLE KINANG
(
	MA_KN CHAR(3),
	TEN_KN NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_KN PRIMARY KEY(MA_KN)
)
GO

CREATE TABLE KIENTHUC
(
	MA_KT CHAR(3),
	TEN_KT NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_KT PRIMARY KEY(MA_KT)
)
GO

CREATE TABLE LOPHOC
(
	MA_LH CHAR(5),
	TEN_LH NVARCHAR(30) NOT NULL,
	MA_VITRI CHAR(3), --FK
	TG_BATDAU DATE NOT NULL,
	TG_KETHUC DATE,
	CONSTRAINT PK_LH PRIMARY KEY(MA_LH)
)
GO

CREATE TABLE KHOAHOC
(
	MA_KH CHAR(5),
	TEN_KH NVARCHAR(30) NOT NULL,
	MUCTIEU NVARCHAR(100),
	HINH_THUC BIT NOT NULL, --0 LÀ OFFLINE, 1 LÀ ONLINE
	GHI_CHU NVARCHAR(100),
	CONSTRAINT PK_KH PRIMARY KEY(MA_KH),
)
GO

CREATE TABLE NOIDUNG
(
	MA_ND CHAR(5),
	TEN_ND NVARCHAR(30) NOT NULL,
	THOILUONG INT NOT NULL,
	MUCTIEU NVARCHAR(100),
	MA_KHOAHOC CHAR(5), --FK
	CONSTRAINT PK_ND PRIMARY KEY(MA_ND)
)
GO

CREATE TABLE TAILIEU
(
	MA_TL CHAR(5),
	TEN_TL NVARCHAR(20) NOT NULL,
	NOIDUNG_TL NVARCHAR(100) NOT NULL,
	MA_NOIDUNG CHAR(5) NOT NULL, --FK
	CONSTRAINT PK_TL PRIMARY KEY(MA_TL)
)
GO

CREATE TABLE DEBAI
(
	MA_DB CHAR(7),
	TEN_DB NVARCHAR(30) NOT NULL,
	LOAI_DB BIT NOT NULL, --0 LÀ BT, 1 LÀ ĐỀ THI
	CONSTRAINT PK_DB PRIMARY KEY(MA_DB)
)
GO

CREATE TABLE DETULUAN
(
	MA_DTL CHAR(9),
	CAUHOI_TL NVARCHAR(200) NOT NULL,
	DAPAN NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_DTL PRIMARY KEY(MA_DTL)
)
GO

CREATE TABLE DETRACNGHIEM
(
	MA_DTN CHAR(9),
	CAUHOI_TN NVARCHAR(200) NOT NULL,
	DAPAN1 NVARCHAR(50) NOT NULL,
	DAPAN2 NVARCHAR(50) NOT NULL,
	DAPAN3 NVARCHAR(50) NOT NULL,
	DAPAN4 NVARCHAR(50) NOT NULL,
	DAPANDUNG INT NOT NULL,
	CONSTRAINT PK_DTN PRIMARY KEY(MA_DTN)
)
GO

CREATE TABLE PHANHOI
(
	STT INT,
	MA_NOIDUNG CHAR(5), --FK
	MA_NGUOIPHANHOI CHAR(5), --FK
	NOIDUNG_PHANHOI NVARCHAR(200),
	CONSTRAINT PK_PH PRIMARY KEY(STT, MA_NOIDUNG)
)
GO

CREATE TABLE CHITIET_NV_KN
(
	MA_NV CHAR(5),
	MA_KN CHAR(3),
	CONSTRAINT PK_CT_NV_KN PRIMARY KEY(MA_NV, MA_KN)
)
GO

CREATE TABLE CHITIET_NV_KT
(
	MA_NV CHAR(5),
	MA_KT CHAR(3),
	CONSTRAINT PK_CT_NV_KN PRIMARY KEY(MA_NV, MA_KT)
)
GO

CREATE TABLE CHITIET_NV_KH
(
	MA_NV CHAR(5),
	MA_KH CHAR(3),
	DANHGIA CHAR(4),
	CONSTRAINT PK_CT_NV_KN PRIMARY KEY(MA_NV, MA_KH),
	CONSTRAINT CONS_DANHGIA CHECK(DANHGIA IN('PASS', 'FAIL'))
)
GO

CREATE TABLE CHITIET_LH_KH
(
	MA_LH CHAR(5),
	MA_KH CHAR(3),
	MA_GIANGVIEN CHAR(5) NOT NULL, --FK
	COTDIEM_BT1 FLOAT,
	COTDIEM_BT2 FLOAT,
	COTDIEM_BT3 FLOAT,
	COTDIEM_BT4 FLOAT,
	COTDIEM_BT5 FLOAT,
	COTDIEM_BT6 FLOAT,
	COTDIEM_BT7 FLOAT,
	COTDIEM_BT8 FLOAT,
	COTDIEM_BT9 FLOAT,
	COTDIEM_BT10 FLOAT,
	COTDIEM_THI FLOAT,
	CONSTRAINT PK_CT_NV_KN PRIMARY KEY(MA_LH, MA_KH)
)
GO

CREATE TABLE CHITIET_LH_NV
(
	MA_LH CHAR(5),
	MA_TRAINEE CHAR(5),
	DANHGIA BIT, --NULL LÀ CHƯA ĐÁNH GIÁ, 0 LÀ FAIL, 1 LÀ PASS
	CONSTRAINT PK_CT_LH_NV PRIMARY KEY(MA_LH, MA_TRAINEE)
)
GO

CREATE TABLE CHITIET_KH_KN
(
	MA_KH CHAR(5),
	MA_KN CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_KH, MA_KN)
)
GO

CREATE TABLE CHITIET_KH_KT
(
	MA_KH CHAR(5),
	MA_KT CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_KH, MA_KT)
)
GO

CREATE TABLE CHITIET_KH_VT
(
	MA_KH CHAR(5),
	MA_VT CHAR(3),
	CONSTRAINT PK_CT_KH_VT PRIMARY KEY(MA_KH, MA_VT)
)
GO

CREATE TABLE CHITIET_VT_KN
(
	MA_VT CHAR(3),
	MA_KN CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_VT, MA_KN)
)
GO

CREATE TABLE CHITIET_VT_KT
(
	MA_VT CHAR(3),
	MA_KT CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_VT, MA_KT)
)
GO

CREATE TABLE CHITIET_PB_KN
(
	MA_PB CHAR(3),
	MA_KN CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_PB, MA_KN)
)
GO

CREATE TABLE CHITIET_PB_KT
(
	MA_PB CHAR(3),
	MA_KT CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_PB, MA_KT)
)
GO

CREATE TABLE CHITIET_DA_KN
(
	MA_DA CHAR(3),
	MA_KN CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_DA, MA_KN)
)
GO

CREATE TABLE CHITIET_DA_KT
(
	MA_DA CHAR(5),
	MA_KT CHAR(3),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_DA, MA_KT)
)
GO

CREATE TABLE CHITIET_DA_NV
(
	MA_DA CHAR(3),
	MA_NV CHAR(5),
	CONSTRAINT PK_CT_KH_KN PRIMARY KEY(MA_DA, MA_NV)
)
GO

CREATE TABLE CHITIET_DB_DTL
(
	MA_DB CHAR(7),
	MA_DTL CHAR(9),
	CONSTRAINT PK_CT_DB_DTL PRIMARY KEY(MA_DB, MA_DTL)
)
GO

CREATE TABLE CHITIET_DB_DTN
(
	MA_DB CHAR(7),
	MA_DTN CHAR(9),
	CONSTRAINT PK_CT_DB_DTN PRIMARY KEY(MA_DB, MA_DTN)
)
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_VT
FOREIGN KEY(MA_VITRI)
REFERENCES VITRI
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_PB
FOREIGN KEY(MA_PHONGBAN)
REFERENCES PHONGBAN
GO

ALTER TABLE LOPHOC
ADD CONSTRAINT FK_LH_VT
FOREIGN KEY(MA_VITRI)
REFERENCES VITRI
GO

ALTER TABLE NOIDUNG
ADD CONSTRAINT FK_ND_KH
FOREIGN KEY(MA_KHOAHOC)
REFERENCES KHOAHOC
GO

ALTER TABLE TAILIEU
ADD CONSTRAINT FK_TL_ND
FOREIGN KEY(MA_NOIDUNG)
REFERENCES NOIDUNG
GO

ALTER TABLE PHANHOI
ADD CONSTRAINT FK_PH_ND
FOREIGN KEY(MA_NOIDUNG)
REFERENCES NOIDUNG
GO

ALTER TABLE PHANHOI
ADD CONSTRAINT FK_PH_NV
FOREIGN KEY(MA_NGUOIPHANHOI)
REFERENCES NHANVIEN
GO

ALTER TABLE CHITIET_NV_KN
ADD CONSTRAINT FK_CTNVKN_NV
FOREIGN KEY(MA_NV)
REFERENCES NHANVIEN
GO

ALTER TABLE CHITIET_NV_KN
ADD CONSTRAINT FK_CTNVKN_KN
FOREIGN KEY(MA_KN)
REFERENCES KINANG
GO

ALTER TABLE CHITIET_NV_KT
ADD CONSTRAINT FK_CTNVKT_NV
FOREIGN KEY(MA_NV)
REFERENCES NHANVIEN
GO

ALTER TABLE CHITIET_NV_KT
ADD CONSTRAINT FK_CTNVKT_KT
FOREIGN KEY(MA_KT)
REFERENCES KIENTHUC
GO

ALTER TABLE CHITIET_NV_KH
ADD CONSTRAINT FK_CTNVKH_NV
FOREIGN KEY(MA_NV)
REFERENCES NHANVIEN
GO

ALTER TABLE CHITIET_NV_KH
ADD CONSTRAINT FK_CTNVKH_KH
FOREIGN KEY(MA_KH)
REFERENCES KHOAHOC
GO

ALTER TABLE CHITIET_LH_KH
ADD CONSTRAINT FK_CTLHKH_LH
FOREIGN KEY(MA_LH)
REFERENCES LOPHOC
GO

ALTER TABLE CHITIET_LH_KH
ADD CONSTRAINT FK_CTLHKH_KH
FOREIGN KEY(MA_KH)
REFERENCES KHOAHOC
GO

ALTER TABLE CHITIET_LH_KH
ADD CONSTRAINT FK_CTLHKH_NV
FOREIGN KEY(MA_GIANGVIEN)
REFERENCES NHANVIEN
GO

ALTER TABLE CHITIET_LH_NV
ADD CONSTRAINT FK_CTLHNV_NV
FOREIGN KEY(MA_TRAINEE)
REFERENCES NHANVIEN
GO

ALTER TABLE CHITIET_LH_NV
ADD CONSTRAINT FK_CTLHNV_LH
FOREIGN KEY(MA_LH)
REFERENCES LOPHOC
GO

ALTER TABLE CHITIET_KH_KN
ADD CONSTRAINT FK_CTKHKN_KH
FOREIGN KEY(MA_KH)
REFERENCES KHOAHOC
GO

ALTER TABLE CHITIET_KH_KN
ADD CONSTRAINT FK_CTKHKN_KN
FOREIGN KEY(MA_KN)
REFERENCES KINHNGHIEM
GO

ALTER TABLE CHITIET_KH_KT
ADD CONSTRAINT FK_CTKHKT_KH
FOREIGN KEY(MA_KH)
REFERENCES KHOAHOC
GO

ALTER TABLE CHITIET_KH_KT
ADD CONSTRAINT FK_CTKHKT_KT
FOREIGN KEY(MA_KT)
REFERENCES KIENTHUC
GO

ALTER TABLE CHITIET_KH_VT
ADD CONSTRAINT FK_CTKHVT_KH
FOREIGN KEY(MA_KH)
REFERENCES KHOAHOC
GO

ALTER TABLE CHITIET_KH_VT
ADD CONSTRAINT FK_CTKHVT_VT
FOREIGN KEY(MA_VT)
REFERENCES VITRI
GO

ALTER TABLE CHITIET_VT_KN
ADD CONSTRAINT FK_CTVTKN_VT
FOREIGN KEY(MA_VT)
REFERENCES VITRI
GO